### ISSUE TITLE
cerc/fixturenet-eth-geth build fails in shiv mode

### ISSUE THREAD

**Issue by zramsay** [cerc-io/stack-orchestrator#123] opened 2023-01-16 17:42 UTC
Running `laconic-so build-containers --include cerc/laconicd,cerc/go-ethereum,cerc/lighthouse,cerc/fixturenet-eth-geth,cerc/fixturenet-eth-lighthouse` (on v1.0.8) led this error. 

```
Removing intermediate container 4f92000a5f43
 ---> 0e1dce78ca3d
Step 11/15 : COPY genesis /opt/testnet
COPY failed: file not found in build context or excluded by .dockerignore: stat genesis: file does not exist
Result is: CompletedProcess(args='/home/hibou/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/app/data/container-build/cerc-fixturenet-eth-geth/build.sh', returncode=1)
Building: cerc/fixturenet-eth-lighthouse
Sending build context to Docker daemon  6.656kB
Step 1/16 : FROM sigp/lcli:v3.2.1 AS lcli
v3.2.1: Pulling from sigp/lcli
e96e057aae67: Pull complete
c3724e486977: Pull complete
Digest: sha256:574022f36658b16583d677ed0fa0d7f56cc2455542a7053ed7b0b8522bf80cdf
Status: Downloaded newer image for sigp/lcli:v3.2.1
 ---> 1c8dfd051c06
Step 2/16 : FROM skylenet/ethereum-genesis-generator@sha256:210353ce7c898686bc5092f16c61220a76d357f51eff9c451e9ad1b9ad03d4d3 AS ethgen
 ---> d49fefd45a03
Step 3/16 : FROM cerc/fixturenet-eth-geth:local AS fnetgeth
pull access denied for cerc/fixturenet-eth-geth, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Result is: CompletedProcess(args='/home/hibou/.shiv/laconic-so_66eb1d30880ab3b4cef6a909f929659e65c357b7b8a1d8314a5e964f28dc6a15/site-packages/app/data/container-build/cerc-fixturenet-eth-lighthouse/build.sh', returncode=1)
```

**Comment by dboreham** [comment] 2023-01-16 17:46
Probably related to this: https://github.com/cerc-io/stack-orchestrator/issues/118
The build of `cerc/fixturenet-eth-geth` failed, but we carried on to try to use it later.

**Comment by zramsay** [comment] 2023-01-16 17:53
ah, great. Now that I think about it - I do recall occasional builds failing, then re-running `build-containers` and magically it worked. Closing in favour of #118  ... I guess the temp solution to the re-run the build

**Comment by dboreham** [comment] 2023-01-16 17:54
Reopening as the reason for this build failure has not been identified.

**Comment by dboreham** [comment] 2023-01-17 04:23
I was able to reproduce this, only with the shiv package (it worked ok in developer mode). Probably to do with the odd way Python zip packages make you access data files.




```
 ./laconic-so build-containers --include cerc/fixturenet-eth-geth
...
Step 11/15 : COPY genesis /opt/testnet
COPY failed: file not found in build context or excluded by .dockerignore: stat genesis: file does not exist
```

**Comment by dboreham** [comment] 2023-01-17 04:58
Should be fixed now: https://github.com/cerc-io/stack-orchestrator/pull/124

**Closed by dboreham** 2023-01-17 04:58 UTC
